import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import joblib

# Load the Iris dataset
iris_df = sns.load_dataset('iris')

# Features and target
X = iris_df.drop('species', axis=1)
y = iris_df['species']

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the model
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

# Save the model
joblib.dump(model, 'random_forest_model.pkl')

In [75]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [76]:
df=sns.load_dataset('iris')
#??
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [77]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [78]:
X=df.drop('species',axis=1)
y=df['species']
# print('X=',X)
# print('y=',y)

In [79]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [80]:
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.2,random_state=42)

In [81]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(random_state=42)

In [82]:
model.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

prediction

In [83]:
y_pred=model.predict(X_test)

In [84]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
#calculate accuracy
accuracy=accuracy_score(y_test,y_pred)
print('accuracy=',accuracy)

print('classification_report=\n',classification_report(y_test,y_pred))
print('confusion_matrix=\n',confusion_matrix(y_test,y_pred))

accuracy= 1.0
classification_report=
               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

confusion_matrix=
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [85]:
predict2=model.predict([[1.2,3.4,2.3,4.1]])
print('predict2=',predict2)

predict2= ['setosa']


c:\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [86]:
a=[1.8,2.7,3.1,1.9]
b=[2.8,2.7,4.1,1.9]
c=[4.8,2.7,7.1,1.9]
d=[6.8,2.7,5.1,1.9]
l=[a,b,c,d]
print('l=',l)
t=len(l)
print('len of l=',t)
for i in range(t):
    print(i)
    prediction=model.predict([l[i]])
    print(prediction)
    #??



l= [[1.8, 2.7, 3.1, 1.9], [2.8, 2.7, 4.1, 1.9], [4.8, 2.7, 7.1, 1.9], [6.8, 2.7, 5.1, 1.9]]
len of l= 4
0
['virginica']
1
['virginica']
2
['virginica']
3
['virginica']


c:\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
c:\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
c:\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
c:\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


evaluate the accuracy

In [87]:
from sklearn.model_selection import cross_val_score
cv_scores=cross_val_score(model,X_train,y_train, cv=5)
print(cv_scores)
print(cv_scores.mean())

[0.95833333 0.95833333 0.83333333 1.         0.95833333]
0.9416666666666667


In [88]:
model.predict([[5.8	,2.7	,5.1	,1.9]])

c:\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array(['virginica'], dtype=object)